name: Publish Laravel App to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v2

      # Build frontend assets
      - name: Install & build frontend assets
        run: |
          npm install
          npm run build

      # Setup PHP and Composer
      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      # Install PHP dependencies for production
      - name: Install Composer dependencies (production)
        run: composer install --no-dev --optimize-autoloader

      # Deploy via FTP (only important files)
      - name: Upload to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          exclude: |
             .git*
              node_modules/**
              vendor/**
              storage/**
              tests/**
              .env
